Upgrade (#136)
* Apply example_ynh

* Fix #49

* Fix #75

* Auto-update README

* Update check_process

Co-authored-by: yunohost-bot <yunohost@yunohost.org>

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -27,18 +27,20 @@ phpversion=$(ynh_app_setting_get --app=$app --key=phpversion)
 #=================================================
 # CHECK VERSION
 #=================================================
+ynh_script_progression --message="Checking version..."
 
 upgrade_type=$(ynh_check_app_version_changed)
 
 #=================================================
 # BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
 #=================================================
-ynh_script_progression --message="Backing up $app before upgrading (may take a while)..." --weight=7
+ynh_script_progression --message="Backing up the app before upgrading (may take a while)..." --weight=7
 
 # Backup the current version of the app
 ynh_backup_before_upgrade
 ynh_clean_setup () {
-	# restore it if the upgrade fails
+	ynh_clean_check_starting
+	# Restore it if the upgrade fails
 	ynh_restore_upgradebackup
 }
 # Exit if an error occurs during the execution of the script
@@ -79,7 +81,12 @@ fi
 
 # Create a permission if needed
 if ! ynh_permission_exists --permission="api"; then
-	ynh_permission_create --permission="api" --url="/api" --allowed="visitors" --show_tile="false" --protected="true"
+	ynh_permission_create --permission="api" --url="/public.php" --allowed="visitors" --show_tile="false" --protected="true"
+fi
+
+# Create a permission if needed
+if ! ynh_permission_exists --permission="public"; then
+	ynh_permission_create --permission="public" --url="/api" --allowed="visitors" --show_tile="false" --protected="true"
 fi
 
 # Do not remove the file before the backup, to not fail the backup.
@@ -92,7 +99,7 @@ ynh_secure_remove --file="/etc/cron.d/$app"
 ynh_script_progression --message="Making sure dedicated system user exists..." --weight=1
 
 # Create a dedicated user (if not existing)
-ynh_system_user_create --username=$app --home_dir=$final_path
+ynh_system_user_create --username=$app --home_dir="$final_path"
 
 #=================================================
 # DOWNLOAD, CHECK AND UNPACK SOURCE
@@ -104,6 +111,7 @@ then
 
 	# Download, check integrity, uncompress and patch the source from app.src
 	ynh_setup_source --dest_dir="$final_path"
+	echo "$(ynh_app_upstream_version)" > "$final_path/version_static.txt"
 fi
 
 chmod 750 "$final_path"
@@ -147,7 +155,7 @@ then
 	ynh_add_config --template="../conf/config.php" --destination="$final_path/config.php"
 
 	ynh_script_progression --message="Upgrading ttrss database..." --weight=2
-	sudo -u $app php${phpversion} ${final_path}/update.php --update-schema=force-yes
+	ynh_exec_as $app php${phpversion} ${final_path}/update.php --update-schema=force-yes
 fi
 
 chmod 400 "$final_path/config.php"
